# **NumPy - "Numerical Python"** (Lib)

<div class="alert alert-block alert-danger">
    <b>Note:</b>If NumPy is not-installed then install using <code>pip install numpy</code>.
</div>

## **Import the NumPy Package**

In [1]:
import numpy as np

***
## **Numpy vs List (Time Taken)**

In [ ]:
from time import process_time

In [ ]:
# Time taken by a list

python_list = [x for x in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

list_time = end_time - start_time

print(list_time)

0.00028313099999977


In [ ]:
# Time taken by a numPy

python_numpy = np.array([x for x in range(10000)])

start_time = process_time()

python_numpy+=5

end_time = process_time()

numpy_time = end_time - start_time
print(numpy_time)

0.00012524399999991331


In [ ]:
diff = list_time - numpy_time
diff

0.00015788699999985667

In [ ]:
fast_percent = diff/numpy_time
fast_percent*=100
fast_percent # How much time numpy is faster than list

126.06352400112257

In [ ]:
(numpy_time*fast_percent/100 + numpy_time) == list_time

True

***
## **Basics**

"The array object in NumPy is called **ndarray**".

### 1-D Array

<code>np.array()</code>

<div class="alert alert-block alert-info">
    <li>
        To create a array
    </li>
    <li>
        To create an ndarray, we can pass a <b>list, tuple or any array-like object</b> into the array() method, and it will be converted into an ndarray.
    </li>
</div>

In [ ]:
num1 = np.array([1,2,3])
num1

array([1, 2, 3])

### 2-D Array

In [ ]:
num2 = np.array([[1,2,3],[4,5,6]])
num2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
temp_num2 = np.array([[1,2],[2,3,4]])
# Each Dimension should have same number of Elements.

/tmp/ipykernel_29248/793099250.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp_num2 = np.array([[1,2],[2,3,4]])


### N-D Array

<code>np.array(,ndmin=N)</code>
<li>
    To set the dimension of the array
</li>

In [ ]:
numN = np.array([1,2,3,4],ndmin=6) #numN have 6 dimension's
numN

array([[[[[[1, 2, 3, 4]]]]]])

***

### Get Dimension Of Array

<code>num.ndim</code>

In [ ]:
num1.ndim

1

In [ ]:
num2.ndim

In [ ]:
numN.ndim

### Get Shape

<code>num.shape</code>

<div class="alert alert-block alert-info">
    Prints number of rows and column for <b>2-D Array.</b> and for <b>N-D Array</b>, prints the number of element in each dimension.
</div>

In [ ]:
num1.shape

In [ ]:
num2.shape

In [ ]:
numN.shape

***

### Get Type

In [ ]:
num1.dtype

In [ ]:
num2.dtype

***

### Declaring Data-Type While Creating Array

<code>np.array([],dtype='')</code>

In [ ]:
num1_16 = np.array([1,2,3],dtype='int16')
num1

In [ ]:
num1_16.dtype

In [ ]:
num1_128 = np.array([1,2,3],dtype='int128')

<div class="alert alert-block alert-danger">
    <b>Note:</b> <code>dtype = 'int8' / 'int16' / 'int32' / 'int64'(default) </code>.
</div>

***

### Get Size of the Element

<code>num.itemsize</code>

<div class="alert alert-block alert-info">
    Print the size of individual element of array in <b>"bytes"</b>
</div>

In [ ]:
num1.itemsize

In [ ]:
num1_16.itemsize

***

### Get Length of the Array

<code>num.size</code>

<div class="alert alert-block alert-info">
    Print the number of elements in the array.
</div>

In [ ]:
num1.size

In [ ]:
num2.size

***

### Get Size of the Array

<code>num.nbytes</code>

<div class="alert alert-block alert-info">
    Print the Total size of the array in <b>"bytes"</b>
</div>

In [ ]:
num1.nbytes

**"OR"**

In [ ]:
num1.itemsize * num1.size

***
## **Accessing Elements**

In [ ]:
num = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
num

In [ ]:
num.shape

### Get Specific Element

<code>[r,c]</code>

In [ ]:
num[1,2]

In [ ]:
num[0,1]

In [ ]:
num[2,1]
## Index Error for Wrong out of Bound

In [ ]:
num[-1]
## Negative indexing works and you can mention the row number to print the row

***

### Get Specific Row

<code>[r,:]</code>

In [ ]:
# First Row [Note: We can print the whole row by not mentioning number of elements.]
num[0,:]

In [ ]:
# Second Row
num[1,:]

***

### Get Specific Column

<code>[:,c]</code>

In [ ]:
# Second Column
num[:,1]

In [ ]:
# First Column
num[:,0]

***

### Slicing

<code>[start_index : end_index : step_size]</code>

<div class="alert alert-block alert-info">
    <b>By Default</b>
    <ul>
        <li>Start Index: 0</li>
        <li>End Index: Length of Array</li>
        <li>Step Size: 1 <b>(Stepsize can't zero)</b></li>
    </ul>
    <p>If we didn't mention any of the parameter, the default value will be taken</p>
    <br>
    <p>Two types of <b>Syntax</b></p>
    <ul>
        <li>
            <code>[start_index : end_index : step_size]</code>
        </li>
        <li>
            <code>[start_index : end_index]</code> (Step size will be 1)
        </li>
    </ul>
</div>

In [ ]:
# without mentioning Start Index, End Index, Step Size with two colon
num[::]

In [ ]:
# without mentioning Start Index, End Index, Step Size with one colon
num[:]

In [ ]:
# Only Mentioning Start Index with two colon
num[1::]

In [ ]:
# Only Mentioning Start Index with one colon
num[1:]

In [ ]:
# Both Start And End with two colon
num[0,0:5:]

In [ ]:
# Both Start And End with one colon
num[0,0:5]

In [ ]:
#  Only End with two colon
num[0,:3:]

In [ ]:
#  Only End with one colon
num[0,:3]

In [ ]:
# Only Step size
num[0,::2]

In [ ]:
# Start and Stepsize

In [ ]:
num[1,2::2]

In [ ]:
# Start, End, Stepsize
num[1,2:7:2]

<div class="alert alert-block alert-info">
    <b>If Stepsize is Negative then By Default</b>
    <ul>
        <li>Start Index: -1</li>
        <li>End Index: -(length of array+1)</li>
        <li>Step Size: Negative Integer></li>
    </ul>
    <p>If we didn't mention any of the parameter, the default value will be taken</p>
    <br>
    <p>Two types of <b>Syntax</b></p>
    <ul>
        <li>
            <code>[start_index : end_index : -i]</code>
        </li>
    </ul>
</div>
<b>Eg:</b>
<img src="../images/Negative_Index_1.jpeg" alt="How Negative Index Labelled" title="Negative Indexing"/>

In [ ]:
# Reverse Order
num[0,::-1] # By default

**OR**

In [ ]:
num[0,-1:-(num[1].size+1):-1]

In [ ]:
# Reverse Order But Only 4 elements
num[0,-1:-5:-1]

In [ ]:
# Negative step size with positive Start Index or End Index
num[0,5::-1]

- When Step size is <b>Positive</b> and either or both of the <b>start and end index</b> is <b>Negative</b> then <b>start and end index</b> will be converted to equivalent <b>Positive Index </b>.

    - In this code snippet <code> num[0,5::-1]</code> Negative Index Equivalent of 5 is -2. So elements from -2 to -8 will be printed
    
- When Step size is <b>Negative</b> and either or both of the <b>start and end index</b> is <b>Positive</b> then <b>start and end index</b> will be converted to equivalent <b>Negative Index </b>.

<img src="../images/Negative_Index_2.jpeg" alt="Reference Image for Negative Indexing" title="Example For Positive Index Equivalent Negative Index "/>

***
### Modifying Elements

In [ ]:
num

In [ ]:
num[1,5] = 20
num[1]

In [ ]:
num[:,2] = 5
num

In [ ]:
num[:,2] = [1,2]
num

In [ ]:
num[1,:] = [x**2 for x in range(0,num[1].size)] # List comprehension
num

***
## **Initializing Different Types Of Array**

### Null / Zero Matrix

<code>np.zeros(dimension of array)</code>
- To create a Array filled with **zero**

In [ ]:
# 1-D Matrix with zero filled
zero_matrix1 = np.zeros(5)
zero_matrix

In [ ]:
# 2-D Matrix with zero filled
zero_matrix2 = np.zeros((5,5))
zero_matrix2

In [ ]:
# N-D Matrix with zero filled
zero_matrixN = np.zeros((5,3,2,2))
zero_matrixN

***

### One Matrix

<code>np.ones(dimension of array)</code>
- To create a Array filled with **ones**

In [ ]:
# N-D Matrix with one filled
one_matrixN = np.ones((3,2,2),dtype='int16')
one_matrixN

***

### "X" Matrix ( x can be any number)

<code>np.full(dimension of array,x)</code>
- To create a Array filled with **desired number**

In [ ]:
matrix2 = np.full((2,3),56,dtype='float32')
matrix2

***
### Creating a Matrix Similar To Another Matrix's Shape

<code>np.full_like(array,x)</code>
- To create a Array filled with **desired number** and **shape will be identical to the mentioned array.**

In [ ]:
temp_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
temp_matrix

In [ ]:
temp_matrix.shape

In [ ]:
similar_matrix = np.full_like(temp_matrix,9,dtype='int16')
similar_matrix

In [ ]:
# Checking whether both matrix's shape is identical
if similar_matrix.shape == temp_matrix.shape:
    print("Shape of the matrix is identical")

***
### Intializing Array With Random Numbers Between 0 and 1

<code>np.random.rand(dimension of array)</code>
- It creates array with **random numbers** between **0 and 1**

In [ ]:
rand_matrix = np.random.rand(3,3)
rand_matrix

***
<code>np.random.random_sample(array.shape)</code>
- It creates array with **random numbers** between **0 and 1** and shape will be similar to the passed array.

In [ ]:
rand_matrix1 = np.random.random_sample(rand_matrix.shape)
rand_matrix1

***
### Intializing Array With Random Numbers Between x and y
<code>np.random.randint(start_index,end_index,size=())</code>

In [ ]:
rand_matrix2 = np.random.randint(7,100,size=(4,3))
rand_matrix2

***
### Identity Matrix
<code>np.identity()</code>

In [ ]:
iden_matrix = np.identity(6)
iden_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
iden_matrix = np.eye(5) # Another Syntax to create identity matrix
iden_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

***
### Repeating Array
<code>np.repeat(array,number_of_times,axis)</code>

In [ ]:
arr = np.array([[x**3 for x in range(4)]])
r1 = np.repeat(arr,3) # without axis
r1

<div class="alert alert-block alert-info">
    <h4>For 2-D Array,</h4>
    <ul>
        <li>
            axis = 0 makes to repeat in y-axis and
        </li>
        <li>
            axis = 1 makes to repeat in x-axis
        </li>
    </ul>
</div>

<div class="alert alert-block alert-info">
    <h4>For 3-D Array,</h4>
    <ul>
        <li>
            axis = 0 makes to repeat in z-axis,
        </li>
        <li>
            axis = 1 makes to repeat in y-axis, and
        </li>
        <li>
            axis = 2 makes to repeat in x-axis
        </li>
    </ul>
</div>







In [ ]:
r2 = np.repeat(arr,2,axis=0)
r2

### Evenly Spaced Array

a<sub>n</sub> = a<sub>1</sub> + (n-1)*d

- n --> Number of Term
- d --> Common Difference

<code>np.linspace(x,y,n)</code> For this syntax Number of terms is used to create a array

Gives 'n' values between 'x' and 'y'. Values will be in Arithmatic Progression

In [ ]:
evenly_spaced = np.linspace(10,30,11,dtype='i')
evenly_spaced

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30], dtype=int32)

<code>np.arange(x,y,d)</code>

Gives  values between 'x' and 'y' with a difference 'd'

In [ ]:
evenly_spaced = np.arange(10,30,8,dtype='i')
evenly_spaced

array([10, 18, 26], dtype=int32)

### Converting List to Array

In [ ]:
list = [1,2,3]
list_to_num = np.array(list)


In [ ]:
#OR
list_to_num = np.asarray(list)
list_to_num

array([1, 2, 3])

---
## **Problem - 1**

<img src="../images/Problem_1.png" alt="Matrix" title="problem-1" height="250px" width="250px"/><br>
**Create the above matrix using learned methods**

In [ ]:
output = np.ones((5,5))
print(output)
"""
My Solution
zero_array3 = np.zeros((3))
output[1,1:4] = zero_array3
print(output)
output[1:4,1] = zero_array3
output[3,1:4] = zero_array3
output[1:4,3] = zero_array3
output[2,2] = 9

"""
#Efficient Solution
temp_zero = np.zeros((3,3))
temp_zero[1,1] = 9
print(temp_zero)

output[1:4,1:4] = temp_zero 

In [ ]:
output

***
### How to copy a array?

In [ ]:
arr1 = np.array([1,2,3])
arr2 = arr1 # reference is copied
arr3 = arr1.copy() # proper way to copy
arr1

In [ ]:
arr2[1] = 5
print(arr1)

In [ ]:
arr3[0] = 10
arr3

In [ ]:
arr1
# When we change elements from arr2, arr1 is affected but
# when we change elements from arr3, arr1 is not affected

In [ ]:
print(arr2.base)
print(arr3.base)

In [ ]:
arr2 = arr1.view()
print(arr2.base)
print(arr3.base)

<div class="alert alert-block alert-danger">
    <h4>Doubt Difference b/w below three intialization</h4>
    <b>arr1 = arr2 <br> arr1 = arr2.view()<br> arr2 = arr1.copy()</b> 
</div>

***
### Converting Data Type on Existing Arrays

<code>array.astype('data_type')</code>
<h4>List of Data Types</h4>

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [ ]:
arr_float = np.array([1.5, 2.21,3.141], dtype='f')
arr_float
# dtype helps to intialize the data_type while creating a array and it's not compulsory

In [ ]:
arr_int = arr_float.astype('i2') #i2 means integer 2 bytes
arr_int

***
## **Mathematics**

In [ ]:
# Creating a Random Array for Testing Mathematics
A = np.random.randint(100,size=(6))
A

array([51, 79, 27, 84, 95, 31])

In [ ]:
B = np.random.randint(100,size=(6))
B

array([51, 44, 66, 74, 12, 58])

### Arithmetic

In [ ]:
A+3

array([4, 5, 6])

In [ ]:
A-3

array([-2, -1,  0])

In [ ]:
A*2

array([2, 4, 6])

In [ ]:
A/2

array([0.5, 1. , 1.5])

In [ ]:
A + B

array([102, 123,  93, 158, 107,  89])

In [ ]:
#OR
np.add(A,B)

array([102, 123,  93, 158, 107,  89])

In [ ]:
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))

[  0  35 -39  10  83 -27]
[2601 3476 1782 6216 1140 1798]
[1.         1.79545455 0.40909091 1.13513514 7.91666667 0.53448276]


***
### Trignometry

In [ ]:
np.sin(A)

In [ ]:
np.cos(B)

***
### Linear Algebra
- Matrix Multiplication
- Determinant
- Trace
- Inverse
- EigenValues
- Matrix Norm
- Inverse

In [ ]:
matA = np.random.randint(6,100,size=(2,3)) #Elements will be in the range(6,100)
print(matA)
matB = np.random.randint(100,size=(3,2))
print(matB)

In [ ]:
# Matrix Multiplication

matC = np.matmul(matA,matB)
matC

In [ ]:
# Find the determinant
det_matC = np.linalg.det(matC)
det_matC

***
### Statistics

In [ ]:
print(matA)
np.min(matA) # Minimum Value from the matrix

In [ ]:
np.max(matA)

In [ ]:
np.min(matA,axis=0) # returns the minimum value from each column

In [ ]:
np.min(matA,axis=1) # returns the minimum value from each row

In [ ]:
np.sum(matA) # Sum of the array

In [ ]:
np.sum(matA,axis=0) # Sum of each column

In [ ]:
np.sum(matA,axis=1) # Sum of each row

***
## **Reorganizing Array**

In [ ]:
initial = np.random.randint(100,size=(4,3))
print(initial)
initial.shape

[[82 47 77]
 [43 89 97]
 [84 82 81]
 [98 49 95]]


(4, 3)

In [ ]:
# Reshaping a Array
final = initial.reshape((2,6))
final
# it is only possible product of inital_dimension is equal to product of final dimension
# or
# number of elemnts in intial should fit into the final array

array([[82, 47, 77, 43, 89, 97],
       [84, 82, 81, 98, 49, 95]])

In [ ]:
# Transpose Of Matrix
transpose = np.transpose(final)
print(transpose)
transpose.shape

[[82 84]
 [47 82]
 [77 81]
 [43 98]
 [89 49]
 [97 95]]


(6, 2)

In [ ]:
transpose1 = final.T
transpose1

array([[82, 84],
       [47, 82],
       [77, 81],
       [43, 98],
       [89, 49],
       [97, 95]])

In [ ]:
final.shape

In [ ]:
final2 = initial.reshape((2,2,3))
final2

In [ ]:
# Vertical Stack
a1 = np.random.randint(20,size=(6))
a2 = np.random.randint(20,size=(6))
print(a1)
print(a2)

In [ ]:
np.vstack([a1,a2])

In [ ]:
np.vstack([a1,a2,a1,a2])

In [ ]:
a3 = np.random.randint(20,size=(5))
a3

In [ ]:
np.vstack([a1,a3]) #Error 

In [ ]:
# Horizontal Stack
print(a1)
print(a2)
np.hstack([a1,a2])

***
## **Load Data From Files**

In [ ]:
filedata = np.genfromtxt('../data/test.txt',delimiter=',')
filedata.astype('i2')
filedata

***
## **Boolean Masking and Advance Indexing**

In [ ]:
filedata > 10

In [ ]:
filedata[filedata >10] # Listing value greater than 10

In [ ]:
filedata

In [ ]:
filedata1 = filedata.reshape((-1)).astype('i2')
filedata1 
# you can mention -1, when yoy don't know the no of eleemnts.
# When there are multiple dimension, you can only mention -1 for any one dimension.

In [ ]:
filedata1[[1,2,6]] # Passing index as a List

# printing the elemnts at index : 1, 2, 6

In [ ]:
print(filedata)
np.any(filedata>3,axis=0) # checking at each column any value is greater than 3

In [ ]:
print(filedata)
np.all(filedata>3,axis=0) # checking at each column all value is greater than 3

In [ ]:
((filedata > 3) & (filedata < 43))

In [ ]:
~((filedata > 3) & (filedata < 43))

***
## **Problem 2**
<img src="../images/Problem_2.png" alt="Problem" title="problem" height=350px width=350px/>

In [ ]:
input = np.array([x for x in range(1,31)])
input[[1,5]]

In [ ]:
input = input.reshape((6,5))
input

In [ ]:
input[2:4,0:2]

In [ ]:
input[[0,1,2,3],[1,2,3,4]]
# First list first element will be paired with second list's first element
#(0,1),(1,2),(2,3),(3,4)

In [ ]:
input[[0,4,5],3:]

***